{% set version = "2.13.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r.filesets
  version: {{ version|replace("-", "_") }}

source:
  fn: R.filesets_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/R.filesets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.filesets/R.filesets_{{ version }}.tar.gz
  sha256: cf1597227bc2cc4b3f4a2bdf087e1ed33330a8450655d6a72236d105f0f39988

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: future (>= 1.7.0), gtools (>= 3.5.0)
requirements:
  host:
    - r-base
    - r-r.cache >=0.13.0
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.21.0
    - r-r.utils >=2.6.0
    - r-digest >=0.6.15
    - r-future.apply >=0.1.0

  run:
    - r-base
    - r-r.cache >=0.13.0
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.21.0
    - r-r.utils >=2.6.0
    - r-digest >=0.6.15
    - r-future.apply >=0.1.0

test:
  commands:
    - $R -e "library('R.filesets')"           # [not win]
    - "\"%R%\" -e \"library('R.filesets')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/R.filesets, http://www.aroma-project.org/
  license: LGPL (>= 2.1)
  summary: 'A file set refers to a set of files located in one or more directories on the file
    system.  This package provides classes and methods to locate, setup, subset, navigate
    and iterate such sets.  The API is designed such that these classes can be extended
    via inheritance to provide a richer API for special file formats.  Moreover, a specific
    name format is defined such that filenames and directories can be considered to
    have full names which consists of a name followed by comma-separated tags.  This
    adds additional flexibility to identify file sets and individual files.  NOTE: This
    package''s API should be considered to be in an beta stage.  Its main purpose is
    currently to support the aroma.* packages, where it is one of the main core components;
    if you decide to build on top of this package, please contact the author first.'

  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
