travis:
  secure:
    BINSTAR_TOKEN: BGPguziRrrcmInKwUb8YSKQlp88RZ+FDe78FP0FTdeijKTKD/V/OeH51xv13418rA8fvTGzmaRukvyaQArnbK94maYtsC+6kJiWOmOPRZCKLQ0MZWeRIqQOIIjKI5OtXvUterQOtqX6vTdOij4zQIjZNetLbu7o+cIPbe7zxCHlIBvf3qw1nq/bs51Yc559qfqMZZu163WrrGu3kVjfrgcwxZ4xxWkfgy/dTiROcSWH90Dfe+vIYNNGQKN2yQ6kR8ZoSvwOG9H60kE9VU1Q8bFwFx52MBi85aYhAINhaPrpsGvgTVVHH+q+2TyTg2oRpSUgffTZRT/bxMcFEjC6VypRsfaTIerKW2cqwgp3XU256YntBl+LcnpjhdrxZ+ATfukvcaurowhEgDgASbIDBPjFb9gspn6siPMHtO8qu+MS2gsv+GHg6sYFjEkgE1p+TPTcnlLt7kA6r7kXAPwSfEp3+QaMdvkUFvc5GvbMFgLAb1dhZ7oFvY5UHOBeRucb8ROB9VRgtPqCGoaKkNkPfdeUwNfbkUnGHs9ZsVtfhaTiFWx/dlt0jesIHeGxQkuj9dXRztaAi32ZqH4GIERDQ7jH0hL0W08I9hAvK36pXk2x9/CYItuKYH6sA/Y7LXRi/HnMpKnkviBsN6r4i8T7KkVi30lfwY/eiVlJqg1P387A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
