travis:
  secure:
    BINSTAR_TOKEN: EivaYi+olVpGQ+dwQL7q4/lTabVPkXHYWGcNphwF600+23mS+BEdVCrcYusYdBqGkD+57LZigmB1+t9cO5VO0KBPfIZgr0kzZNeWw4LwxxnHIO78fuoa8pGk4wHMM+91Ldg3q0h8H0xyrCgTZWWorJxsh6+4eWlR81ZFnmx3nt633q2NBMdj+sPdlfaGHGjivNCeDHu8oz5Z1Hx+icmA4KnYB/eeRcvoMzNU/9Rm7bhRO0Lebsodzo1vOv6NClTMHLjEalJa27qt/YOP+dr5roHPDQ2OL5rwyZLXhPYY3Mhnm60eQhjcNeHYBgfAd2hvP+SyEFHmKMK93DMJaj7avjSLsoVthDnO1qaBlHTFDR5mSJGhIn2EeH45MiWrFkKStJ7suJqk5tYc25qF8g0mN/T/93gevjOfifvYuo+he2Vc6uv2xu69iTaxoWPKytlpgr1rWtpYsJZ15xcf66xnDCH9eFq6s+Hs98ne3mz4L6Xco5wxvJ7p+uy08PkMoV2I9FxeCZKwBJM2n43GRVfhk4Y2nilSniyXHyCApzmy8tlsefF+h8uOApsqLEAKIQUPz8OIG++5uKxMDjzH13BOcTstmITeTqMMKJWIUWUMwo56W3Kn0uyoPfUjT/fMcGUfv4ZBtiSAHZr5QtH0isMBcbtXx+pKbRNcpP5V+jnSgwE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
